services:
  - type: web
    name: polaroo-gmail-system
    runtime: python
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install chromium
      python -m playwright install-deps chromium
    startCommand: python -m uvicorn src.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        generateValue: true
      - key: PYTHONPATH
        value: .
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    healthCheckPath: /api/health